Repository ironcore-dev/boot-operator, pull requests merged in 2025-07, with the labels that each got.

#173 Support OCI Spec Published under Ironcore
  cmd/main.go
  go.mod
  go.sum
  internal/controller/serverbootconfiguration_http_controller.go
  internal/controller/serverbootconfiguration_http_controller_test.go
  internal/controller/serverbootconfiguration_pxe_controller.go
  internal/controller/serverbootconfiguration_pxe_controller_test.go
  server/imageproxyserver.go
Labels: enhancement, api-change, area/metal-automation, ok-to-image

#198 Add size GH workflow
  .github/workflows/size-label.yml
Labels: chore

#199 Update dependabot config and license footer
  .github/dependabot.yml
  .github/workflows/auto-merge.yaml
  README.md
Labels: documentation, chore, size/M
